project:
  type: website
  output-dir: docs
  resources:
  - CNAME

pagetitle: "{{< meta title >}} | Matthew Martin"
author-meta:  "Matthew Martin"

website:
  title: "Matthew Martin"
  google-analytics: "G-EL33VJN6EN"
  site-url: https://mattjamesmartin.github.io/
  repo-url: https://github.com/mattjamesmartin/mattjamesmartin.github.io

  open-graph: 
    image: "imgs/headshot.jpg"
    locale: en_US
  
  twitter-card:
    image: "imgs/headshot.jpg"
    creator: "@MattJ_Martin"
    card-style: summary
    
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "Research"
        href: "research/index.qmd"
      - text: "Teaching"
        href: "teaching/index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Blog"
        href: "blog/index.qmd"
        
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:mjmartin@utexas.edu"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/mattjamesmartin
      - text: "{{< iconify bi bluesky size=1em title='Bluesky' >}}"
        href: https://bsky.app/profile/mattjmartin.com
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/mattj-martin/
        rel: me
      - text: "{{< iconify bi orcid size=1.1em title='Orcid' >}}"
        href: https://orcid.org/0000-0003-3460-3603

  page-footer:
    left: |
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>
    background: light
  
format:
  html:
    include-after-body: tracking.html
    theme:
      - html/mattjamesmartin.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
  
editor: visual